a2lix_translation_form:
    locale_provider: default
    locales: '%locales%'
    default_locale: '%locale%'
    required_locales: '%locales%'
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"