# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    locales: [en, ru, bg]
    currency: 'EUR'
    locale_currencies: [ EUR, USD, GBP,BGN,RUB]
    uploads_dir: '%kernel.project_dir%/public/assets/images'
    uploads_temp_dir: '%uploads_dir%/temp'
    user_image_dir: '%uploads_dir%/avatar'
    logo_image_temp_dir: '%uploads_dir%/temp/logo'
    logo_image_dir: '%uploads_dir%/logo'
    currencies: 'https://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml'
    uploads_property_temp_dir: '%uploads_dir%/temp/property'
    uploads_property: '%uploads_dir%/properties/property'
    uploads_property_widget_temp_dir: '%uploads_dir%/temp/property/widget'
    uploads_widget_property: '%uploads_dir%/properties/widgets/widget'
    uploads_property_plan_temp_dir: '%uploads_dir%/temp/property/plan'
    uploads_plan_property: '%uploads_dir%/properties/plans/plan'
    stripe_secret_key: sk_test_mtN1VNsFAX1UehiyS8VTYdij
    stripe_public_key: pk_test_iIczhUVzKPAtVepamOHMWG5u
services:
    app.menu_builder:
        class: App\Menu\UserMenu\Builder
        arguments: [ "@knp_menu.factory" ]
    userSmallMenu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.menu_builder", userSmallMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: smallMenu }
    userMenu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.menu_builder", userMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: userMenu }
    adminMenu:
        class: Knp\Menu\MenuItem
        factory: [ "@app.menu_builder", adminMenu ]
        arguments: [ "@request_stack" ]
        tags:
            - { name: knp_menu.menu, alias: adminMenu }
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
